baseurl: https://reddavid.me
languageCode: en-us
theme: hugo-theme-stack-master
paginate: 7
title: Red David

languages:
  en:
    languageName: English
    title: David Ballesteros
    weight: 1

staticDir:
  - static

# Change it to your Disqus shortname before using
disqusShortname: reddavid-me

ogImage: "images/reddavid-og.png"
# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: featuredimage, image
  ogImageField: ogimage
  rssFullContent: true
  favicon:

  footer:
    since: 2019
    customText: All Rights Reserved

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: 👋
    subtitle: IT Guy | App Dev | Gamer
    avatar:
      enabled: true
      local: false
      src: "/images/avatar.jpg"

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: disqus

    disqusjs:
      shortname:
      apiUrl:
      apiKey:
      admin:
      adminLabel:

    utterances:
      repo:
      issueTerm: pathname
      label:

    remark42:
      host:
      site:
      locale:

    vssue:
      platform:
      owner:
      repo:
      clientId:
      clientSecret:
      autoCreateIssue: false

    # Waline client configuration see: https://waline.js.org/en/reference/client.html
    waline:
      serverURL:
      lang:
      visitor:
      avatar:
      emoji:
        - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
      requiredMeta:
        - name
        - email
        - url
      placeholder:
      locale:
        admin: Admin

    twikoo:
      envId:
      region:
      path:
      lang:

    # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
    cactus:
      defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
      serverName: "cactus.chat"
      siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

    giscus:
      repo:
      repoID:
      category:
      categoryID:
      mapping:
      lightTheme:
      darkTheme:
      reactionsEnabled: 1
      emitMetadata: 0

    gitalk:
      owner:
      admin:
      repo:
      clientID:
      clientSecret:

    cusdis:
      host:
      id:
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site: reddvid

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: false
      src: "/images/reddavid-og-new.png"

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: dark

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: []

  social:
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/reddvid
      params:
        icon: brand-twitter

    - identifier: github
      name: GitHub
      url: https://github.com/reddvid
      params:
        icon: brand-github

    - identifier: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/reddvid
      params:
        icon: brand-linkedin

    - identifier: twitch
      name: Twitch
      url: https://twitch.com/reddavidgg
      params:
        icon: brand-twitch

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
