baseurl: https://reddavid.me
languageCode: en-us
theme: hugo-theme-stack-3.17.0
paginate: 7
title: Red David Blog

languages:
  en:
    languageName: English
    title: David Ballesteros
    description: Personal blog about life, tech, gaming, coding, and music
    weight: 1

staticDir:
  - static

# Change it to your Disqus shortname before using
disqusShortname: https-reddavid-me

ogImage: "images/reddavid-og.png"
# GA Tracking ID
googleAnalytics: UA-129071597-1

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: featuredimage, image
  ogImageField: ogimage
  rssFullContent: true
  favicon:

  footer:
    since: 2019
    customText: Some Rights Reserved. I don't know, do I need a lawyer?

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 PHST

  sidebar:
    emoji: 👋
    subtitle: Systems and IT Engineer | Applications Developer
    avatar:
      enabled: true
      local: false
      src: "/images/avatar.jpg"

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: "reddvid/reddvid.github.io"
      repoID: "MDEwOlJlcG9zaXRvcnkxNzc0NDEzMDE="
      category: "General"
      categoryID: "DIC_kwDOCpOKFc4CT3lg"
      mapping: "pathname"
      lightTheme: "light"
      darkTheme: "dark"
      reactionsEnabled: 0
      emitMetadata: 0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site: reddvid

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: false
      src: "/images/reddavid-og-new.png"

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: dark

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: []

  social:
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/reddvid
      params:
        icon: brand-twitter

    - identifier: instagram
      name: Instagram
      url: https://instagram.com/reddvid
      params:
        icon: brand-instagram

    - identifier: github
      name: GitHub
      url: https://github.com/reddvid
      params:
        icon: brand-github

    - identifier: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/reddvid
      params:
        icon: brand-linkedin

    - identifier: youtube
      name: YouTube
      url: https://youtube.com/@reddavid
      params:
        icon: brand-youtube

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 3

# caches:
#   getcsv:
#     dir: :cacheDir/:project
#     maxAge: "30m"

